export type ErrorCode =
  | 'INTERNAL_ERROR' | 'UNAUTHORIZED' | 'FORBIDDEN' | 'NOT_FOUND'
  | 'VALIDATION_FAILED' | 'CONFLICT'
  | 'RESERVATION_NOT_FOUND' | 'RESERVATION_ALREADY_CANCELLED' | 'RESERVATION_CANNOT_CANCEL' | 'RESERVATION_STATUS_INVALID'
  | 'PAYMENT_FAILED' | 'PAYMENT_METHOD_NOT_FOUND' | 'PAYMENT_REFUND_FAILED'
  | 'USER_NOT_FOUND' | 'INVALID_CREDENTIALS' | 'EMAIL_ALREADY_EXISTS' | 'SESSION_EXPIRED'
  | 'DOCUMENT_NOT_FOUND' | 'DOCUMENT_UPLOAD_FAILED' | 'FILE_TOO_LARGE'
  | 'CONVERSATION_NOT_FOUND' | 'MESSAGE_NOT_FOUND' | 'NOT_PARTICIPANT' | 'EDIT_WINDOW_EXPIRED'
  | 'CONTRACT_NOT_FOUND' | 'CONTRACT_ALREADY_SIGNED'
  | 'CALENDAR_SYNC_FAILED'
  | 'INVOICE_NOT_FOUND' | 'INVOICE_PDF_FAILED'
  | 'PROFILE_NOT_FOUND' | 'CATEGORY_NOT_FOUND' | 'REVIEW_NOT_FOUND'
  | 'KYC_DOCUMENT_NOT_FOUND' | 'NOTIFICATION_NOT_FOUND'
  | 'TEMPLATE_NOT_FOUND' | 'TEMPLATE_ALREADY_EXISTS'
  | 'DEVIATION_REPORT_NOT_FOUND' | 'SECTION_NOT_FOUND'
  | 'FINAL_REPORT_NOT_FOUND' | 'REPORT_STATUS_INVALID'
  | 'FOLDER_NOT_FOUND' | 'ATTACHMENT_NOT_FOUND'
  | 'NORM_NOT_FOUND' | 'AUDIT_TYPE_NOT_FOUND'
  | 'EMPTY_CONTENT' | 'ALREADY_ARCHIVED' | 'NOT_ARCHIVED'
  | 'COMMISSION_NOT_FOUND' | 'PAYMENT_NOT_FOUND' | 'CUSTOMER_NOT_FOUND'
  | 'LEGAL_STATUS_NOT_FOUND' | 'CONTESTATION_NOT_FOUND' | 'CONNECTION_NOT_FOUND'
  | 'TICKET_NOT_FOUND' | 'INSTANCE_NOT_FOUND' | 'BILLING_ADDRESS_NOT_FOUND'
  | 'COMPETENCY_DOCUMENT_NOT_EDITABLE' | 'REVIEW_ALREADY_EXISTS';

export interface ApiErrorResponse {
  code: ErrorCode;
  message: string;
  status: number;
  details?: unknown[];
}
